CREATE TABLE "mellowboard_cron_status" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"status" varchar(100),
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "mellowboard_logs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"user_id" uuid NOT NULL,
	"type" "log_type" NOT NULL,
	"status" "log_status" NOT NULL,
	"points" integer NOT NULL,
	"task_date" timestamp,
	"created_at" timestamp DEFAULT now()
);
--> statement-breakpoint
CREATE TABLE "mellowboard_post" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "mellowboard_post_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256),
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE "mellowboard_users" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"name" varchar(100) NOT NULL,
	"freeze_card_count" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "mellowboard_users_name_unique" UNIQUE("name")
);
--> statement-breakpoint
ALTER TABLE "mellowboard_logs" ADD CONSTRAINT "mellowboard_logs_user_id_mellowboard_users_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."mellowboard_users"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "name_idx" ON "mellowboard_post" USING btree ("name");